### ISSUE TITLE
Add alpha channel and html color code box

### ISSUE THREAD

**Issue by Chozzle** [Madrapps/Pikolo#23]
Hi,
I might be able to work on this myself. I need these functions for my app.

**Comment by thsaravana** [comment]
Great. We were planning to generalize the HSL picker to support HSLA, RGB, RGBA, etc... The idea was to create a generic arc slider that can be H or S or R or anything. We would really like to add the Alpha Arc slider on top of such a framework rather to the existing one. So that in future, any one can write their own version of arc slider and add that to Pikolo. And we welcome your contribution towards that.

As for the Html color code box, we don't want to tie that with Pikolo. Pikolo already exposes callbacks with the color being selected. You can use this to update anything (like a html color code box).

You can always fork Pikolo and modify it as you want and use that in your app.

**Comment by thsaravana** [comment]
We will support Alpha and any other Channel after we generalize the `ArcComponent`. So closing this for now.
